---
name: 'CI'

on:
  push:
    branches: ['trunk']
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.golangci.yml'
      - '.builds/'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches: ['trunk']
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.golangci.yml'
      - '.builds/'
      - 'LICENSE.md'
      - 'README.md'

permissions:
  contents: read

jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: 'Tests'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4.2.2
        with:
          persist-credentials: false

      - name: 'Setup Go environment'
        uses: 'actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a' # v5.2.0
        with:
          go-version: '>=1.23'

      - name: 'Run tests'
        run: 'make test'
